
INSERT INTO ROLE (ID, NAME) VALUES (1, 'SECRETARIA');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'DOCTOR');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'PACIENTE');

INSERT INTO USER_ (ID, NAME, PASSWORD) VALUES (1, 'secretaria', 'uVQoLxtZvlhBuamIlWRLGQ==');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);

INSERT INTO USER_ (ID, NAME, PASSWORD) VALUES (2, 'doctor', 'uVQoLxtZvlhBuamIlWRLGQ==');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);

INSERT INTO USER_ (ID, NAME, PASSWORD) VALUES (3, 'paciente', 'uVQoLxtZvlhBuamIlWRLGQ==');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 3);


COMMIT;